# Foot Segmentation Model Configuration

# Model Configuration
model:
  type: 'unet'  # Options: 'unet', 'deeplabv3plus', 'fpn'
  encoder: 'resnet50'  # Options: 'resnet50', 'efficientnet-b4', 'timm-resnest50d'
  num_classes: 2

# Training Configuration
training:
  img_size: 512
  batch_size: 8
  learning_rate: 1e-4
  weight_decay: 1e-4
  epochs: 100
  num_workers: 4
  
# Data Configuration
data:
  data_dir: '../data'
  train_split: 0.8
  val_split: 0.2
  
# Augmentation Configuration
augmentation:
  horizontal_flip: 0.5
  brightness_contrast: 0.3
  color_jitter: 0.3
  gaussian_noise: 0.2
  random_crop: 0.3
  
# Logging Configuration
logging:
  use_wandb: true
  project_name: 'foot-segmentation'
  save_dir: '../models'
  log_interval: 10
  
# Inference Configuration
inference:
  confidence_threshold: 0.5
  min_area: 1000
  postprocess: true